name: Server-Manager
authors: [novastosha, diniamo]
description: The way to manage your server
version: 0.1 IN-DEV
main: ServerManager
commands:
  gamemode:
    description: Switches your gamemode.
    aliases: [gm]
#depend: [Skript]