name: Server Manager
author: [novastosha,diniamo]
description: THe way to manage your server
version: 1.0
main: main.java.ServerManager
commands:
    gms:
        description: Switches your gamemode to Survival
    gmp:
      description: Switches your gamemode to Spectator
    gma:
      description: Switches your gamemode to Adventure
    gmc:
      description: Switches your gamemode to Creative
#depend: [Skript]